spring.application.name=javacup-backend
server.port=8080

# Application info
application.version=@project.version@
application.name=@project.name@
application.description=@project.description@

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
